# Static analysis workflow 2 (static_analysis_2.yml)
# This workflow is triggered only when a pull request is created.
name: Static Analysis on Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run Static Analysis Tool
        run: flake8 .
